## 詞頻矩陣

In [9]:
import jieba
jieba.load_userdict('userdict.txt')
ary = ['富邦人壽首創保費1萬就能刷卡',
       '富邦人壽不老勇士Go來盃3對3籃賽南北開打',
       '富邦人壽不老勇士Go來盃開打']

In [10]:
corpus = []
for title in ary:
    corpus.append(' '.join(jieba.cut(title)))

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer() 

X = vectorizer.fit_transform(corpus)

In [12]:
X.shape

(3, 11)

In [13]:
vectorizer.get_feature_names()

['go', '不老', '人壽', '保費', '刷卡', '勇士', '南北', '富邦', '籃賽', '開打', '首創']

In [14]:
X.toarray()

array([[0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1],
       [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0]], dtype=int64)

## 相似度計算

In [17]:
a = '柯P 大巨蛋 遠雄'
b = '柯P 為了 大巨蛋 一案 找 遠雄 算帳'

#   柯P 大巨蛋 遠雄 為了 一案 找 算帳
# a  1    1    1    0    0   0   0
# b  1    1    1    1    1   1   1

In [25]:
import numpy as np
na = np.array([1,1,1,0,0,0,0])
nb = np.array([1,1,1,1,1,1,1])

np.sqrt(sum((nb - na) ** 2))

2.0

In [27]:
sum(na * nb) / (np.sqrt(sum(na ** 2)) * np.sqrt(sum(nb ** 2)) )

0.6546536707079772

In [23]:
a = '柯P 大巨蛋 遠雄'
b = '柯P 為了 大巨蛋 一案 找 遠雄 算帳 因為 遠雄 在 這案 中 出爾反爾'

#   柯P 大巨蛋 遠雄 為了 一案 找 算帳 因為 在 這案 中 出爾反爾
# a  1    1    1    0    0   0   0  0   0   0   0    0
# b  1    1    2    1    1   1   1  1   1   1   1    1

In [28]:
import numpy as np
na = np.array([1,1,1,0,0,0,0,0,0,0,0,0,0])
nb = np.array([1,1,2,1,1,1,1,1,1,1,1,1,1])

np.sqrt(sum((nb - na) ** 2))

3.3166247903553998

In [29]:
sum(na * nb) / (np.sqrt(sum(na ** 2)) * np.sqrt(sum(nb ** 2)) )

0.57735026918962584

In [31]:
import jieba
jieba.load_userdict('userdict.txt')
ary = ['富邦人壽首創保費1萬就能刷卡',
       '富邦人壽不老勇士Go來盃3對3籃賽南北開打',
       '富邦人壽不老勇士Go來盃開打']
corpus = []
for title in ary:
    corpus.append(' '.join(jieba.cut(title)))
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer() 

X = vectorizer.fit_transform(corpus)
X.toarray()

array([[0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1],
       [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0]], dtype=int64)

In [32]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(X)

array([[ 1.        ,  0.31622777,  0.4       ],
       [ 0.31622777,  1.        ,  0.79056942],
       [ 0.4       ,  0.79056942,  1.        ]])

In [33]:
from sklearn.metrics.pairwise import cosine_distances
cosine_distances(X)

array([[ 0.        ,  0.68377223,  0.6       ],
       [ 0.68377223,  0.        ,  0.20943058],
       [ 0.6       ,  0.20943058,  0.        ]])

## 新聞推薦引擎

In [45]:
import requests
from bs4 import BeautifulSoup
news_ary = []
for page in range(1,30):
    res = requests.get('https://tw.appledaily.com/new/realtime/{}'.format(page))
    soup = BeautifulSoup(res.text, 'html.parser')
    for rec in soup.select('.rtddt a'):
        dic = {}
        dic['link'] = rec['href']
        res2 = requests.get(dic['link'])
        soup2 = BeautifulSoup(res2.text, 'html.parser')
        dic['category'] = soup2.select('.current')[2].text
        dic['title']    = soup2.select_one('h1').text
        dic['content']  = soup2.select_one('.ndArticle_margin p').text
        news_ary.append(dic)
    print(page)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [46]:
import pandas
newsdf = pandas.DataFrame(news_ary)
newsdf.to_excel('appledaily20171214.xlsx')

In [48]:
import pandas
newsdf = pandas.read_excel('data/appledaily20171214.xlsx')

In [49]:
newsdf.head()

category                                            content  \
0       政治  新增：立委說法民進黨立法院黨團預計在明天的院會中，讓改制農田水利會的《農田水利會組織通則》修...   
1       論壇  邱俊棠／台中市民、見習醫師；曾任台灣醫學生聯合會對外副會長對於公民參與公眾事務而能得到單位首...   
2       社會  被控來台涉發展情報組織的中國學生周泓旭，因接觸我方外交部官員而露餡落網，今年9月被台北地院一...   
3       生活  【廣編特輯】 對於全能神教會在中國所遭受的迫害與在韓國、香港及臺灣所面對的反面宣傳，非政府組...   
4       生活  立法院交通委員會今審查《道路交通管理處罰條例》，通過營業大客車駕駛人行駛一般道路未繫安全帶，...   

                                                link  \
0  https://tw.news.appledaily.com/politics/realti...   
1  https://tw.news.appledaily.com/forum/realtime/...   
2  https://tw.news.appledaily.com/local/realtime/...   
3  https://tw.news.appledaily.com/life/realtime/2...   
4  https://tw.news.appledaily.com/life/realtime/2...   

                            title  
0  【更新】水利會改官派明闖關　綠委24小時前顧議場大門防藍突襲  
1               請中市府為所當為 加速中火燃煤限制  
2              陸生共諜嗆台司法　「不敢公開審理我」  
3             【特企】NGO聯名譴責中共迫害宗教信仰  
4       乘客搭大客車不配合繫安全帶　立院初審通過可罰6千元

In [52]:
corpus = []
titles = []
for news in newsdf.iterrows():
    corpus.append(' '.join(jieba.cut(news[1]['content'])))
    titles.append(news[1]['title'])

In [56]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
X

<899x38624 sparse matrix of type '<class 'numpy.int64'>'
	with 128131 stored elements in Compressed Sparse Row format>

In [67]:
from sklearn.metrics.pairwise import cosine_similarity
cs = cosine_similarity(X)
cs.shape

(899, 899)

In [65]:
na = np.array([1,9,2,6,8,4,5,7])
na.sort()
na

array([1, 2, 4, 5, 6, 7, 8, 9])

In [66]:
na = np.array([1,9,2,6,8,4,5,7])
na.argsort()

array([0, 2, 5, 6, 3, 7, 4, 1], dtype=int64)

In [72]:
rank = cs[0].argsort()[::-1]
for rec in rank[0:10]:
    if cs[0][rec] > 0.3:
        print(titles[rec], cs[0][rec])

【更新】水利會改官派明闖關　綠委24小時前顧議場大門防藍突襲 1.0
反對水利會改制　吳敦義下令：藍委做好夜宿立院抗爭準備 0.367845249572
農田水利會改公務機關　蔡英文：這不是綁樁 0.327587152559


In [73]:
def getSimiliarArticle(pos):
    rank = cs[pos].argsort()[::-1]
    for rec in rank[0:10]:
        similiarities = cs[pos][rec]
        if similiarities > 0.3:
            print(titles[rec], similiarities)

In [79]:
getSimiliarArticle(6)

喬妹升格宋太太首上工　現身中國見習近平 1.0
素顏依舊完美　喬妹升格人妻赴中開工 0.31870904608


## 保險常見問題集

In [81]:
import requests
from bs4 import BeautifulSoup
res = requests.get('https://my83.com.tw/knowledge/client')
soup = BeautifulSoup(res.text, 'html.parser')

In [89]:
qalist =  soup.select('.accordionList')
questions = [qa.select('dt')[0].text for qa in qalist]
answers   = [qa.select('dd')[0].text for qa in qalist]
qa_ary 
for q, a in zip(questions, answers):
    dic{'question'} = q
    dic{'answer'}   = a

{'Q：「實支實付」和「定額給付」各是什麼？哪個比較好？': '以上兩種皆是醫療險的理賠方式。實支實付：符合理賠情況，在限額內，花費多少、保險公司理賠多少；超過限額，則最多只理賠到限額。定額給付：又稱為日額給付，符合理賠情況，保險公司按照固定的金額(住院天數 x 每日給付)做理賠，而不管保戶實際上到底花了多少錢。因應二代健保及DRGs(住院診斷關聯群)的實施，使得住院天數大幅下降且醫療自費項目增加，實支實付會較能因應醫療花費。',
 'Q：什麼是竊盜險？': '竊盜險是保險公司提供整台車被偷走或整車損毀的保障，不理賠零件的損失，另外竊盜險會因為車子的年費而折舊，所以不是每輛車都需要投保。',
 'Q：刷卡買機票已經有送旅平險了，還需要另外買旅平險嗎？': '一般信用卡送的旅平險其實是「飛行平安險」，「飛行平安險」只保障搭機前後5小時及飛行途中這段期間，所以建議大家要另外買旅平險來保障常見的海外就醫及意外身故。',
 'Q：只要需要長期看護，長期看護險就可以理賠？': '錯！須符合各家保險公司所定義的長期看護狀態，通常以巴氏量表為準，且每半年至一年要再回診，確保符合長期看護險的失能狀態。',
 'Q：壽險最主要的保障是什麼？長輩似乎都買來做為儲蓄工具': '一般常見的壽險，例如：利率變動型終身壽險、利率變動型還本終身保險、增額終身壽險其實都是儲蓄混合保障的保單，功能混和在一起不僅擠壓到保障額度，儲蓄的報酬率也不佳。',
 'Q：夫妻倆和剛出生的小孩，到底需不需要保險？': '保險是提供您與家人的保障，就像勞保和健保一樣，保障您的醫療品質及職涯發展；有了小孩後，責任漸增，更需要做足全家人的保障。',
 'Q：想投資，銀行定存還是儲蓄險比較好？': '想買儲蓄險，首先要百分百確定，自己在繳費期間不會動用這筆錢。如果在儲蓄險繳費期間內解約，保費會損失且只能拿回解約金；而銀行定存的話，在繳費期間內解約，所繳的費用不會有損失且會加上利息全數退還給你。以剛出社會、不確定何時會用到大筆費用的小資族來說，會建議做銀行定存。',
 'Q：意外險是定期型的比較好還是還本型?': '還本型意外險其實是有儲蓄功能的保險，還本型意外險的保費非常昂貴，是定期型意外險保費的幾十倍，如果把還本意外險的保費拿去定存，所得的利息都可以讓你買到更高保障額的定期意外險了。如果只需要意外險的保障，建議選擇定期

## 同義詞

In [16]:
synonym_dic = {
    '柯P': '柯文哲'
}
s = '柯P為了大巨蛋一案找遠雄算帳'
' '.join([synonym_dic.get(ele, ele) for ele in jieba.cut(s)])


'柯文哲 為 了 大巨蛋 一案 找遠 雄算帳'